// Generates src/countries-data.ts: every region's name in the languages quanto has grammars and month
// names for, from the runtime's ICU data. Addresses name their country in those languages
// ("Deutschland", "Allemagne"), and formatting names it in the reader's. Run with
// `bun scripts/generate-countries.ts`; the output is reviewed and committed, never read from Intl at runtime.

import { writeFileSync } from 'node:fs';
import { REGION_CODES } from '../../../scripts/icu';

/** The languages names are generated for, in the order the table stores them. */
const LANGUAGES = ['en', 'de', 'es', 'fr', 'it', 'nl', 'pt'] as const;

const rows = [...REGION_CODES].sort().map((code) => {
  const names = LANGUAGES.map((language) => new Intl.DisplayNames([language], { type: 'region' }).of(code) ?? code);
  return `  ${code}: ${JSON.stringify(names)},`;
});

const out = `// Generated by scripts/generate-countries.ts. Do not edit by hand.
// Source: the ICU data of the generating runtime.

/** The languages of each row in \`COUNTRY_NAMES\`, in order. */
export const NAME_LANGUAGES: readonly string[] = ${JSON.stringify(LANGUAGES)};

/** Each ISO 3166-1 region's name, in \`NAME_LANGUAGES\` order. */
export const COUNTRY_NAMES: Readonly<Record<string, readonly string[]>> = {
${rows.join('\n')}
};
`;

writeFileSync(new URL('../src/countries-data.ts', import.meta.url), out);
console.log(`wrote ${rows.length} regions`);
