// Generated by scripts/generate-names.ts. Do not edit by hand.
// Source: the ICU data of the generating runtime.

import type { Names } from '../calendar/names';

/** Spanish month and weekday names. */
export const es: Names = {
  language: 'es',
  months: [["enero","ene"],["febrero","feb"],["marzo","mar"],["abril","abr"],["mayo","may"],["junio","jun"],["julio","jul"],["agosto","ago"],["septiembre","sept"],["octubre","oct"],["noviembre","nov"],["diciembre","dic"]],
  weekdays: [["lunes","lun"],["martes"],["miércoles","mié"],["jueves","jue"],["viernes","vie"],["sábado","sáb"],["domingo","dom"]],
  fillers: ["de","del"],
};

/** French month and weekday names. */
export const fr: Names = {
  language: 'fr',
  months: [["janvier","janv"],["février","févr"],["mars"],["avril","avr"],["mai"],["juin"],["juillet","juil"],["août"],["septembre","sept"],["octobre","oct"],["novembre","nov"],["décembre","déc"]],
  weekdays: [["lundi","lun"],["mardi"],["mercredi","mer"],["jeudi","jeu"],["vendredi","ven"],["samedi","sam"],["dimanche","dim"]],
  fillers: ["le"],
};

/** German month and weekday names. */
export const de: Names = {
  language: 'de',
  months: [["Januar","Jan"],["Februar","Feb"],["März","Mär"],["April","Apr"],["Mai"],["Juni","Jun"],["Juli","Jul"],["August","Aug"],["September","Sep","Sept"],["Oktober","Okt"],["November","Nov"],["Dezember","Dez"]],
  weekdays: [["Montag","Mo"],["Dienstag","Di"],["Mittwoch","Mi"],["Donnerstag","Do"],["Freitag","Fr"],["Samstag","Sa"],["Sonntag","So"]],
  fillers: [],
};

/** Italian month and weekday names. */
export const it: Names = {
  language: 'it',
  months: [["gennaio","gen"],["febbraio","feb"],["marzo","mar"],["aprile","apr"],["maggio","mag"],["giugno","giu"],["luglio","lug"],["agosto","ago"],["settembre","set"],["ottobre","ott"],["novembre","nov"],["dicembre","dic"]],
  weekdays: [["lunedì","lun"],["martedì"],["mercoledì","mer"],["giovedì","gio"],["venerdì","ven"],["sabato","sab"],["domenica","dom"]],
  fillers: ["di","del"],
};

/** Portuguese month and weekday names. */
export const pt: Names = {
  language: 'pt',
  months: [["janeiro","jan"],["fevereiro","fev"],["março","mar"],["abril","abr"],["maio","mai"],["junho","jun"],["julho","jul"],["agosto","ago"],["setembro","set"],["outubro","out"],["novembro","nov"],["dezembro","dez"]],
  weekdays: [["segunda-feira","seg","segunda"],["terça-feira","ter","terça"],["quarta-feira","qua","quarta"],["quinta-feira","qui","quinta"],["sexta-feira","sex","sexta"],["sábado","sáb"],["domingo","dom"]],
  fillers: ["de","do","da"],
};

/** Dutch month and weekday names. */
export const nl: Names = {
  language: 'nl',
  months: [["januari","jan"],["februari","feb"],["maart","mrt"],["april","apr"],["mei"],["juni","jun"],["juli","jul"],["augustus","aug"],["september","sep"],["oktober","okt"],["november","nov"],["december","dec"]],
  weekdays: [["maandag","ma"],["dinsdag","di"],["woensdag","wo"],["donderdag","do"],["vrijdag","vr"],["zaterdag","za"],["zondag","zo"]],
  fillers: [],
};
