// Generates src/names/data.ts: month and weekday names for the languages quanto-datetime exports as
// opt-in name sets (`date({ names: [de] })`), from the runtime's ICU data. Run with
// `bun scripts/generate-names.ts`; the output is reviewed and committed, never read from Intl at runtime.

import { writeFileSync } from 'node:fs';

/** Words that sit between a date's parts and are skipped when parsing: "2 de octubre de 2026". */
const FILLERS: Readonly<Record<string, readonly string[]>> = {
  es: ['de', 'del'],
  fr: ['le'],
  de: [],
  it: ['di', 'del'],
  pt: ['de', 'do', 'da'],
  nl: [],
};

const ENGLISH_MONTHS = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'sept', 'oct', 'nov', 'dec', 'january', 'february', 'march', 'april', 'june', 'july', 'august', 'september', 'october', 'november', 'december'];

const strip = (s: string): string => s.replace(/\.$/, '');
const fold = (s: string): string => strip(s).normalize('NFD').replace(/\p{M}/gu, '').toLowerCase();
const unique = (forms: string[]): string[] => forms.filter((f, i) => forms.findIndex((g) => fold(g) === fold(f)) === i);

function month(lang: string, i: number, opts: Intl.DateTimeFormatOptions, inDate: boolean): string {
  const d = new Date(Date.UTC(2026, i, 2));
  if (!inDate) return new Intl.DateTimeFormat(lang, { ...opts, timeZone: 'UTC' }).format(d);
  return new Intl.DateTimeFormat(lang, { ...opts, day: 'numeric', timeZone: 'UTC' }).formatToParts(d).find((p) => p.type === 'month')!.value;
}

const weekday = (lang: string, i: number, style: 'long' | 'short'): string =>
  new Intl.DateTimeFormat(lang, { weekday: style, timeZone: 'UTC' }).format(new Date(Date.UTC(2026, 0, 5 + i))); // 2026-01-05 is a Monday

const sets: string[] = [];
for (const lang of Object.keys(FILLERS)) {
  // Each month: full name first, then the abbreviation format prints, then other accepted forms.
  const months = Array.from({ length: 12 }, (_, i) =>
    unique([month(lang, i, { month: 'long' }, false), month(lang, i, { month: 'short' }, false), month(lang, i, { month: 'long' }, true), month(lang, i, { month: 'short' }, true)].map(strip)),
  );
  const monthKeys = new Set([...months.flat().map(fold), ...ENGLISH_MONTHS]);
  const weekdays = Array.from({ length: 7 }, (_, i) => {
    const long = weekday(lang, i, 'long');
    // "segunda-feira" is often written "segunda".
    const forms = unique([long, strip(weekday(lang, i, 'short')), ...(long.includes('-') ? [long.split('-')[0]!] : [])]);
    // Months win: a weekday form that's also a month name (Spanish "mar") is dropped.
    const kept = forms.filter((f) => !monthKeys.has(fold(f)));
    for (const f of forms) if (!kept.includes(f)) console.log(`${lang}: dropped weekday "${f}", which is also a month name`);
    return kept;
  });
  sets.push(`/** ${new Intl.DisplayNames('en', { type: 'language' }).of(lang)} month and weekday names. */
export const ${lang}: Names = {
  language: '${lang}',
  months: ${JSON.stringify(months)},
  weekdays: ${JSON.stringify(weekdays)},
  fillers: ${JSON.stringify(FILLERS[lang])},
};`);
}

const out = `// Generated by scripts/generate-names.ts. Do not edit by hand.
// Source: the ICU data of the generating runtime.

import type { Names } from '../calendar/names';

${sets.join('\n\n')}
`;
writeFileSync(new URL('../src/names/data.ts', import.meta.url), out);
console.log(`name sets: ${Object.keys(FILLERS).join(', ')}`);
