// Generates src/calendar/regions.ts: each region's numeric date order and clock (12- or 24-hour), from
// the runtime's ICU data. Month and weekday names are in src/calendar/names.ts. Run with
// `bun scripts/generate-locale-data.ts`; the output is reviewed and committed, never read from Intl at
// runtime.

import { writeFileSync } from 'node:fs';
import { lines, regionTable } from '../../../scripts/icu';

/** [dateOrder, hourCycle] */
type Row = [string, number];

function calendar(tag: string): Row {
  const df = new Intl.DateTimeFormat(`${tag}-u-ca-gregory-nu-latn`, { year: 'numeric', month: 'numeric', day: 'numeric' });
  const order = df
    .formatToParts(new Date(2026, 2, 4))
    .filter((p) => p.type === 'year' || p.type === 'month' || p.type === 'day')
    .map((p) => p.type[0]!.toUpperCase())
    .join('');
  // quanto supports MDY, DMY and YMD. Anything else (Kyrgyzstan's YDM) maps by whether the day comes
  // before the month, which is what matters for reading numeric dates.
  const supported = order === 'MDY' || order === 'DMY' || order === 'YMD' ? order : order.indexOf('D') < order.indexOf('M') ? 'DMY' : 'MDY';
  const cycle = new Intl.DateTimeFormat(`${tag}-u-nu-latn`, { hour: 'numeric' }).resolvedOptions().hourCycle;
  return [supported, cycle === 'h11' || cycle === 'h12' ? 12 : 24];
}

const { regions, exceptions } = regionTable(calendar);

const out = `// Generated by scripts/generate-locale-data.ts. Do not edit by hand.
// Source: the ICU data of the generating runtime.

/** [numeric date order, hour cycle] */
export type CalendarRow = readonly ['MDY' | 'DMY' | 'YMD', 12 | 24];

/** Each region's numeric date order and clock. */
export const CALENDAR: Readonly<Record<string, CalendarRow>> = {
${lines(regions)}
};

/** Language-region combinations whose date order or clock differs from their region's. */
export const CALENDAR_EXCEPTIONS: Readonly<Record<string, CalendarRow>> = {
${lines(exceptions)}
};
`;

writeFileSync(new URL('../src/calendar/regions.ts', import.meta.url), out);
console.log(`regions: ${regions.length}, exceptions: ${exceptions.length}`);
