// Generates src/locale/data.ts: the number conventions every codec needs, per region, and the likely
// region of each language. Domain packages generate their own region data (currencies, date order, …).
//
// quanto never reads Intl at runtime (DESIGN.md, Principle 8): the data is generated once, here,
// reviewed, and committed. Run with `bun scripts/generate-locale-data.ts`.

import { writeFileSync } from 'node:fs';
import { LANGUAGES, lines, normalizeSeparator, REGION_CODES, regionTable } from '../../../scripts/icu';

/** [decimal, group, secondaryGroupSize, minimumGroupingDigits] */
type Row = [string, string, number, number];

function numbers(tag: string): Row {
  const nf = new Intl.NumberFormat(`${tag}-u-nu-latn`);
  const parts = nf.formatToParts(12345678.5);
  const decimal = normalizeSeparator(parts.find((p) => p.type === 'decimal')!.value);
  const group = normalizeSeparator(parts.find((p) => p.type === 'group')?.value ?? ',');
  const integers = parts.filter((p) => p.type === 'integer').map((p) => p.value.length);
  const secondary = integers.length >= 3 ? integers[integers.length - 2]! : 3;
  const minGrouping = nf.formatToParts(1234).some((p) => p.type === 'group') ? 1 : 2;
  return [decimal, group, secondary, minGrouping];
}

const { regions, exceptions } = regionTable(numbers);
const likely = [...LANGUAGES]
  .sort()
  .map((language): [string, string | undefined] => [language, new Intl.Locale(language).maximize().region])
  .filter((pair): pair is [string, string] => pair[1] !== undefined && REGION_CODES.includes(pair[1]));

const out = `// Generated by scripts/generate-locale-data.ts. Do not edit by hand.
// Source: the ICU data of the generating runtime.

/** [decimal, group, secondaryGroupSize, minimumGroupingDigits] */
export type NumberRow = readonly [string, string, number, number];

/** Number conventions per region. */
export const REGIONS: Readonly<Record<string, NumberRow>> = {
${lines(regions)}
};

/** Language-region combinations whose number conventions differ from their region's. */
export const EXCEPTIONS: Readonly<Record<string, NumberRow>> = {
${lines(exceptions)}
};

/** The likely region for a tag that has only a language. */
export const LIKELY_REGIONS: Readonly<Record<string, string>> = {
${lines(likely)}
};
`;

writeFileSync(new URL('../src/locale/data.ts', import.meta.url), out);
console.log(`regions: ${regions.length}, exceptions: ${exceptions.length}, languages: ${likely.length}`);
